### ISSUE TITLE
esult::unwrap()` on an `Err` value: "Unsupported OS: android"

### ISSUE THREAD

**Issue by diamantisk** [pykeio/ort#106]
How to build it for android?
I use it as a dependency and it does not work, while in README you mention that android is supported but just not tested.

**Comment by decahedron1** [comment]
Sorry, that error message should say "Microsoft does not provide prebuilt binaries for this platform. You'll need to build ONNX Runtime from source." I fixed this in v2 but forgot to backport the change.

Android is supported, you just need to compile ONNX Runtime from source. See [ONNX Runtime docs](https://onnxruntime.ai/docs/build/android.html) and [ort's docs to point it to your binaries](https://github.com/pykeio/ort/tree/main?tab=readme-ov-file#how-to-get-binaries).
