### ISSUE TITLE
Access to compose API

### ISSUE THREAD

**Issue by miguelaeh** [pykeio/ort#107]
Hi!
It seems the [compose API](https://onnx.ai/onnx/api/compose.html) is not yet implemented. Are there any plans for it?

**Comment by decahedron1** [comment]
I believe you are confusing
- [ONNX](https://onnx.ai/), the library for reading and writing `.onnx` formatted models,
- and [ONNX Runtime](https://onnxruntime.ai/), an inference engine to run those ONNX models.

`ort` is a wrapper around ONNX Runtime only, thus it can't implement or use ONNX's Composer API.

**Comment by miguelaeh** [comment]
Ah, I see, thanks!
