### ISSUE TITLE
`build.rs` will panic on windows when run as regular user.

### ISSUE THREAD

**Issue by Fancyflame** [pykeio/ort#116]
https://github.com/pykeio/ort/blob/584a6e3479dcdc4ea97e5886f569101c758a6384/ort-sys/build.rs#L278-L279

This code will panic if it doesn't run as administrator on windows.
Please consider replacing it with or falling back to copying the file directly.
```rust
#[cfg(windows)] 
std::fs::copy(&lib_path, out_path).unwrap(); 
```

**Comment by decahedron1** [comment]
I'm aware of this. It can be fixed by enabling "Developer Mode" in Settings > For developers (W11). Windows is odd 🙃

I'm currently overhauling the `build.rs`; soon it'll fall back to copying if symlinking is not available.
