### ISSUE TITLE
Possibility to statically link onnxruntime

### ISSUE THREAD

**Issue by beqabeqa473** [pykeio/ort#117]
Hello.

Is there a possibility to statically link onnxruntime with ORT rust crate?

Thanks.

**Comment by decahedron1** [comment]
Yes, just compile ONNX Runtime from source and [point `ort` to the build output](https://github.com/pykeio/ort/tree/main?tab=readme-ov-file#strategies). The new [v2](https://github.com/pykeio/ort/tree/v2) branch provides precompiled static libraries as well.

**Comment by beqabeqa473** [comment]
i have a static library, which contains everything inside.
i put it in onnx/onnxruntime.lib
i've set a variable
set ORT_STRATEGY=system
set ORT_LIB_LOCATION=E:\temp\onnx
it is still trying to load library dynamically

**Comment by decahedron1** [comment]
Try putting it in a new `lib` folder: `E:\temp\onnx\lib` (keep the `ORT_LIB_LOCATION` the same)

**Comment by beqabeqa473** [comment]
ok, did onnx\lib\onnxruntime.lib, onnx\include

Should i put something in cargo?
It is default_feature=false for now.

**Comment by decahedron1** [comment]
No other Cargo features are required.

**Comment by beqabeqa473** [comment]
then for some reason it is not working

**Comment by decahedron1** [comment]
Please upload the output from `cargo build`.

**Comment by beqabeqa473** [comment]
There are no errors, only compilation stuff. When i am trying to run a result, it is trying to load aonnxruntime.dll near the executable

**Comment by decahedron1** [comment]
What command did you use to compile the static library?

**Comment by beqabeqa473** [comment]
i downloaded it from here.
https://github.com/csukuangfj/onnxruntime-build

looking to size, it seems it is static, 242 mb

**Comment by decahedron1** [comment]
Hmm, try this one: https://parcel.pyke.io/v2/delivery/ortrs/packages/msort-binary/1.16.2/ortrs-msort_static-v1.16.2-x86_64-pc-windows-msvc.zip

What is the error you get at runtime? Just to make sure, the `load-dynamic` feature is disabled (or `default-features = false`), correct?

**Comment by beqabeqa473** [comment]
error is the same, could not load library onnxruntime.dll, in cargo default_feature is false, no other libraries are present.

**Comment by decahedron1** [comment]
Please upload a screenshot or log file or other media that shows the error in its entirety.

What version of `ort` do you have specified, v1.16 or v2? I cannot reproduce this with either.

**Comment by beqabeqa473** [comment]
ihave v1.16.3

**Comment by beqabeqa473** [comment]
Unfortunately, for now i am not able to upload a screenshot.


E:\testproj\target\release>testproj.exe
thread '<unnamed>' panicked at C:\Users\beqap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-1.16.3\src\lib.rs:79:83:
could not load the library at `E:\testproj\target\release/onnxruntime.dll`: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
could not load the library at `E:\testproj\target\release/onnxruntime.dll`: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }

**Comment by decahedron1** [comment]
The `load-dynamic` feature is enabled, either in your Cargo manifest or via a dependency that then depends on `ort`.

**Comment by beqabeqa473** [comment]
Yes, you are right. I missed one of dependencies.

Sorry for disturbing and thanks.

**Comment by Lixuhuilll** [comment]
I tried to statically compile onnxruntime on my own, but the compilation product is a lot of scattered .libs instead of one onnxruntime.lib, how do I link it in this case? Or is there something wrong with my compilation?

**Comment by decahedron1** [comment]
@Lixuhuilll Nope, that's normal, and `ort` will link to those just fine.

**Comment by Lixuhuilll** [comment]
> 不，这很正常，并且会很好地链接到这些。`ort`

But I get the following error when statically linking, the onnxruntime that I compiled statically by myself doesn't have this file, only dynamic libraries have this file and the corresponding dlls, and according to the content of https://github.com/microsoft/onnxruntime/issues/8555, these scattered libs can be linked and used one by one. I don't know why ort always tries to find onnxruntime.lib.

LINK : fatal error LNK1181: cannot open input file 'onnxruntime.lib'

**Comment by lacker** [comment]
In case other people are running into `cannot open input file 'onnxruntime.lib'` on Windows with static builds, I found that the problem was that the ORT_LIB_LOCATION was slightly set wrong. What worked for me was:

```
set "ORT_LIB_LOCATION=%PATH_TO_STUFF%\onnxruntime\build\Windows\Release"
cargo build --release --target x86_64-pc-windows-msvc
```

The error message is a bit misleading because there is no "onnxruntime.lib" file anywhere. But that's fine. The real problem is that it wasn't looking in the right directory for the libs.
