### ISSUE TITLE
Error: Missing Input past_key_values.0.key when Running Session with ONNX Model

### ISSUE THREAD

**Issue by YuriyKrasilnikov** [pykeio/ort#123]
I've encountered a problem, and I can't find any examples or solutions for the ort library anywhere on the internet. I really hope for the community's help. I would also appreciate any possible code improvements.

### Issue Description
Encountered an error indicating a missing input for past_key_values.0.key when running an ONNX model session using the ort crate (version 1.16.3) in Rust. The model was converted using optimum-cli specifically for the task text-generation-with-past.

### Code to Reproduce
```
use std::{
    io::{self, Write},
    path::Path,
};

use ndarray::{Array, IxDyn, ArrayBase, Data, CowRepr, CowArray};
use ndarray_rand::RandomExt;
use ndarray_rand::rand_distr::Uniform;

use ort::{GraphOptimizationLevel, SessionBuilder, Environment, Value};
use tokenizers::Tokenizer;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let environment = Environment::builder()
        .with_name("OpenChat")
        .build()?
        .into_arc();

    let model_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("onnx/model.onnx");

    let session = SessionBuilder::new(&environment)?
        .with_optimization_level(GraphOptimizationLevel::Level1)?
        .with_model_from_file(model_path)?;

    let tokenizer_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("onnx/tokenizer.json");
    let tokenizer = Tokenizer::from_file(tokenizer_path)
        .map_err(|e| e as Box<dyn std::error::Error>)?;

    let input_text = "Write the story of Little Red Riding Hood";
    let tokens = tokenizer.encode(input_text, false).unwrap();
    let token_ids = tokens.get_ids().iter().map(|&id| id as i64).collect::<Vec<_>>();
    
    let shape = IxDyn(&[1, 12, token_ids.len() - 1, 64]);

    let input_array = Array::from_shape_vec(IxDyn(&[1, token_ids.len()]), token_ids)?;

    let cow_tensor: CowArray<i64, IxDyn> = CowArray::from(input_array);

    let mut past_key_values = Vec::new();
    for _ in 0..12 {
        let random_array = Array::random(shape.clone(), Uniform::new(0i64, 1i64));
        let cow_array: CowArray<i64, IxDyn> = CowArray::from(random_array);
        past_key_values.push(cow_array);
    }

    let mut dynamic_past_key_values = Vec::new();
    for cow_array in past_key_values {
        dynamic_past_key_values.push(cow_array.into_dyn());
    }

    let binding = cow_tensor.into_dyn();
    let input_value = Value::from_array(
        session.allocator(),
        &binding,
    )?;

    let mut inputs = vec![input_value];

    for dyn_array in dynamic_past_key_values.iter() {
        inputs.push(
            Value::from_array(
                session.allocator(),
                dyn_array
            )?
        );
    }
    let outputs = session.run(inputs)?;

    for output in outputs {
        println!("{:?}", output);
    }

    Ok(())
}
```

### Error Message
`Error: SessionRun(Msg("Non-zero status code returned while running Shape node. Name:'/model/Shape_1' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:42 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: past_key_values.0.key\n"))`

### Expected Behavior
The session to run without errors, processing the input tensor correctly.

### Actual Behavior
The session failed with an error related to a missing input past_key_values.0.key.

### Environment
Rust version: 1.74.0
ONNX model details: Model converted with optimum-cli for text-generation-with-past task
OS: Linux 5.15.133.1-microsoft-standard-WSL2

**Comment by decahedron1** [comment]
Looking at optimum's docs it seems `text-generation-with-past` shouldn't have these inputs. Is the model you are trying to export supported by Optimum?

**Comment by YuriyKrasilnikov** [comment]
This issue for Python is discussed, for example, here:
https://github.com/huggingface/optimum/issues/552

**Comment by YuriyKrasilnikov** [comment]
@decahedron1 
I also assume that it is necessary to get the names and shape from the model first, as is done in the example for C++ https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/model-explorer/model-explorer.cpp

Note that 
```
 // print name/shape of inputs
  Ort::AllocatorWithDefaultOptions allocator;
  std::vector<std::string> input_names;
  std::vector<std::int64_t> input_shapes;
  std::cout << "Input Node Name/Shape (" << input_names.size() << "):" << std::endl;
  for (std::size_t i = 0; i < session.GetInputCount(); i++) {
    input_names.emplace_back(session.GetInputNameAllocated(i, allocator).get());
    input_shapes = session.GetInputTypeInfo(i).GetTensorTypeAndShapeInfo().GetShape();
    std::cout << "\t" << input_names.at(i) << " : " << print_shape(input_shapes) << std::endl;
  }
  // some models might have negative shape values to indicate dynamic shape, e.g., for variable batch size.
  for (auto& s : input_shapes) {
    if (s < 0) {
      s = 1;
    }
  }
```

Since I tried to make a model without past_key_values, I ran into the problem of having other named entities:
`Error: SessionRun(Msg("Non-zero status code returned while running Reshape node. Name:'/model/Reshape' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:42 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: position_ids\n"])))`
