### ISSUE TITLE
Cache downloaded libs

### ISSUE THREAD

**Issue by mush42** [pykeio/ort#130]
Hi

I'm using ort v2.0.0-alpha2 and it seams like ort re-downloads static library builds every time I switch build profile or I don't work on the project for a long time.

This is very inconvenient for people like me who have a very limited connection most of the time.

Is there any way to automatically cache downloaded libs once and reuse them for subsequent builds.

I think this is also good for pykeio server's bandwidth.

Best
Musharraf

**Comment by decahedron1** [comment]
> I think this is also good for pykeio server's bandwidth.

Good idea =)

**Comment by decahedron1** [comment]
Added in https://github.com/pykeio/ort/commit/52559e49da6963e12ab715d70dc47bb9b721489e
