### ISSUE TITLE
How can I check if onnx is using cuda, and does the session live for the duration of the application, or is it recreated every time?

### ISSUE THREAD

**Issue by rlewkowicz** [pykeio/ort#132]
I've tried many implementations of yolov8 via rust and ort. It's very slow. I tried explicitly setting `[ExecutionProvider::CUDA(CUDAExecutionProviderOptions::default())]` and it doesn't seem to make a difference. I did this on session builder so it should crap out if it can't use cuda?

That leads me to think it's reinitializing the environment. I'm fresh to rust, so I'm not sure if this actually doing what I think:
```
static ENV: OnceCell<Mutex<Arc<Environment>>> = OnceCell::new();

fn ensure_env() -> &'static Mutex<Arc<Environment>> {
    return ENV.get_or_init(|| Mutex::new(Arc::new(Environment::builder().with_name("YOLOv8").build().unwrap())));
}

static MODEL: OnceCell<Mutex<Session>> = OnceCell::new();

fn ensure_model() -> &'static Mutex<Session> {
   return MODEL.get_or_init(|| Mutex::new(SessionBuilder::new(&ensure_env().lock().unwrap()).unwrap().with_execution_providers([ExecutionProvider::CUDA(CUDAExecutionProviderOptions::default())]).unwrap().with_model_from_file("C:\\Repos\\ultralytics\\weights\\best.onnx").unwrap()));
}
```

Ideally, the runtime env is primed and then I'm just using as needed to run the inference.

**Comment by decahedron1** [comment]
> I tried explicitly setting `[ExecutionProvider::CUDA(CUDAExecutionProviderOptions::default())]` and it doesn't seem to make a difference. I did this on session builder so it should crap out if it can't use cuda?

`ort` is designed to [gracefully fallback to CPU](https://ort.pyke.io/perf/execution-providers#fallback-behavior) when no execution providers succeed to register.

To troubleshoot why CUDA is not registering, you'll need to set up a subscriber for `tracing` messages, see here: https://ort.pyke.io/troubleshooting/performance#my-ep-doesnt-seem-to-work

To programmatically determine whether EP registration succeeds, there is a new API in ort `v2.0.0-alpha.2` - `ExecutionProvider::register`. I highly recommend [updating to the v2 alpha](https://ort.pyke.io/migrating/v2) as there were also a few performance fixes that might help.
```rs
use ort::{CUDAExecutionProvider, ExecutionProvider, Session};

fn main() -> anyhow::Result<()> {
    let builder = Session::builder()?;

    let cuda = CUDAExecutionProvider::default();
    if cuda.register(&builder).is_err() {
        eprintln!("Failed to register CUDA!");
        std::process::exit(1);
    }

    let session = builder.with_model_from_file("model.onnx")?;

    Ok(())
}
```

> does the session live for the duration of the application, or is it recreated every time?

Sessions and environments last until they are dropped. If you're wrapping them in a `OnceCell`, then they are only ever created once.
