### ISSUE TITLE
Does 2.0.0-alpha.2 have ORT_LIB_LOCATION 

### ISSUE THREAD

**Issue by rlewkowicz** [pykeio/ort#133]
Per your recommendation, I've tried 2.0.0. I have tried various feature options to no avail. I cannot get cuda to load on windows 11. I'm wondering if it's grabbing the wrong dlls.

Does 2.0.0 have ORT_LIB_LOCATION  or similar?

I should add, I've used cuda across a variety of languages, os, versions, etc. In all instances I've been successful. I've tried 11.6 and 12.3 with NVIDIA GeForce RTX 4090 Laptop GPU.

**Comment by decahedron1** [comment]
Yes, the 2.0.0-alpha.2 still has the same `ORT_LIB_LOCATION` configuration option, see here: https://ort.pyke.io/setup/linking#linking-to-a-custom-build-of-onnx-runtime

> I have tried various feature options to no avail. I cannot get cuda to load on windows 11.

Is it failing to compile, or failing to register at runtime? What do the logs say?

**Comment by rlewkowicz** [comment]
My first issue is that for some reason, envs set with `set` didn't register.  I had to use: ` $env:ORT_DYLIB_PATH="C:\Repos\...`. Now with tracing and, in this case dynamic libs, all I get is the "Failed to register CUDA!" generated below.

```
        let cuda = CUDAExecutionProvider::default();

        let builder = Session::builder().unwrap();
        
        if cuda.register(&builder).is_err() {
            eprintln!("Failed to register CUDA!");
            std::process::exit(1);
        }
```

Other than that, it's just failing silently. I'm loading the latest 16.3 dll. Now onnxruntime_providers_cuda.dll exists, but idk how that gets loaded. The path has to be onnxruntime.dll or the application panics.

**Comment by rlewkowicz** [comment]
```
Error: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Repos\rust-yolo\rust-yolo\lib\onnxruntime_providers_cuda.dll"
```
This definitely exists. So it looks like it checks the same folder, but it can't open it or something. I'll try the 16.2 module.

**Comment by decahedron1** [comment]
Often times I found that error (confusingly) means the CUDA EP itself could not load a dependency DLL. The EP is being loaded fine, but CUDA is not. Ensure you have CUDA 11.8 installed (12.x will not work). You may be missing `zlibwapi.dll` as well.

**Comment by rlewkowicz** [comment]
It was CUDNN missing:
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
https://developer.nvidia.com/rdp/cudnn-download
I just put them in the cuda path.
