### ISSUE TITLE
it take long time to load 

### ISSUE THREAD

**Issue by NofAssiri** [pykeio/ort#135]
i have 150MB onnx model that takes about 10 minutes to load, but when using onnxruntime crate with the same version of onnxruntime.dll 1.16.3 it loads in 4, or 5 seconds
platform: 
      windows 11 pro 64-bit build 22621 
processor: 
     12th Gen Intel Core i7-12800HX
chip Type: 
      AMD Software: Pro Edition 0x73E1 VRAM 8GB
Ram: 
       32GB

code used 
       let _session = Session::builder().expect("builder error ")
        .with_optimization_level(ort::GraphOptimizationLevel::Disable).expect("opt level error 14")
         .with_optimization_level(GraphOptimizationLevel::Level1).unwrap()
         .with_model_from_file("C:\\models\\model.onnx").expect("model file error 15");

**Comment by decahedron1** [comment]
Can't reproduce this with a 1.5 GB model, it consistently takes ~5 seconds. Either way `with_model_from_file` has ONNX Runtime  loading the file, so there isn't anything I could do to fix this on my end. Maybe there's an issue with your C: drive? Is it an HDD?

**Comment by NofAssiri** [comment]
@decahedron1 no the C drive is SSD, i tried using ort_sys directly it gives the same result, thanks in advance.

**Comment by NofAssiri** [comment]
turns out that onnxruntime crate wasn`t happy with onnxruntime.dll version that i provided so it was using the one in the system32 folder.
