### ISSUE TITLE
ort 1.16 is not compatible with the ONNX Runtime binary found at `onnxruntime.dll`; expected GetVersionString to return '1.16.x', but got '1.10.0'

### ISSUE THREAD

**Issue by monkeycc** [pykeio/ort#141]
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-Rust

`cargo run --release -- --cuda --model <MODEL> --source <SOURCE>`

https://github.com/microsoft/onnxruntime/releases
https://github.com/microsoft/onnxruntime/releases/download/v1.16.3/onnxruntime-win-x64-gpu-1.16.3.zip

`ORT_LIB_LOCATION=D:\onnxruntime-win-x64-gpu-1.16.3\lib`

**ort 1.16 is not compatible with the ONNX Runtime binary found at `onnxruntime.dll`; expected GetVersionString to return '1.16.x', but got '1.10.0'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

**Comment by decahedron1** [comment]
The example uses `load-dynamic` so `ORT_LIB_LOCATION` does nothing. You should be setting `ORT_DYLIB_PATH=D:\onnxruntime-win-x64-gpu-1.16.3\lib\onnxruntime.dll` instead.
