### ISSUE TITLE
When using shared memory, I need to manually specify input and output to reduce memory copying

### ISSUE THREAD

**Issue by soloist-v** [pykeio/ort#144]
In `value.rs` modify `let shape = self.0.clone();`  to `let shape = self.0;`
```Rust
impl<T: Clone + Debug + 'static> OrtInput for (Vec<i64>, Arc<Box<[T]>>) {
	fn into_parts(mut self) -> (Vec<i64>, *mut Self::Item, usize, Box<dyn Any>) {
		let shape = self.0.clone();  // let shape = self.0;
		let ptr = std::sync::Arc::<std::boxed::Box<[T]>>::make_mut(&mut self.1).as_mut_ptr();
		let ptr_len: usize = self.1.len();
		let guard = Box::new(Arc::clone(&self.1));
		(shape, ptr, ptr_len, guard)
	}
}
```
Can we add the following implementation：
```Rust
impl<'a, T: Clone + Debug + 'static> crate::value::OrtInput for (Vec<i64>, &'a [T]) {
	type Item = T;

	fn ref_parts(&self) -> (Vec<i64>, &[Self::Item]) {
		let shape = self.0.clone();
		let data = self.1;
		(shape, data)
	}

	fn into_parts(self) -> (Vec<i64>, *mut Self::Item, usize, Box<dyn Any>) {
		let shape = self.0;
		let ptr = self.1.as_ptr() as *mut T;
		let ptr_len: usize = self.1.len();
		let guard = Box::new(());
		(shape, ptr, ptr_len, guard)
	}
}
```

**Comment by decahedron1** [comment]
> Can we add the following implementation：

The data contained in a `Value` must last at least as long as the value itself. We can't guarantee this for slices without copying the data into the value. Is there a reason you can't use `Arc<Box<[T]>>`?

**Comment by soloist-v** [comment]
When I use shared memory, I need to customize the allocator. I tried Arc<Box<[T]>, but I got the following error：
```error[E0277]: the trait bound `Value: From<(Vec<i64>, Arc<Box<[f32], MyAllocator>>)>` is not satisfied```
In addition, can Arc<Box<T>>be replaced with Arc<[T]>.
