### ISSUE TITLE
Can't run ort with opencv

### ISSUE THREAD

**Issue by yevhen-k** [pykeio/ort#145]
Can't run ort 2.0.0-alpha.4 with opencv 0.88.7 on my linux machine (haven't tried win/mac). Here is the simplest set up for repro.

sample.rs
```rust
use opencv;
use ort;
use tracing_subscriber;

fn main() -> Result<(), Box<dyn std::error::Error>> { Ok(()) }
```

Cargo.toml
```toml
[package]
# ...
edition = "2021"

[[bin]]
name = "sample"
path = "src/sample.rs"

[dependencies]
opencv = { version = "0.88.7" }
ort = "2.0.0-alpha.4"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
```

Compilation
```bash
RUST_LOG="ort=debug" cargo run --bin sample
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1705669118.540041   29440 descriptor_database.cc:633] File already exists in database: 
F0000 00:00:1705669118.540077   29440 descriptor.cc:2120] Check failed: GeneratedDatabase()->Add(encoded_file_descriptor, size) 
*** Check failure stack trace: ***
[1]    29440 IOT instruction (core dumped)  RUST_LOG="ort=debug" cargo run --bin sample
```

**Comment by decahedron1** [comment]
Sorry but this isn't anything ort can fix.

See here: https://groups.google.com/g/protobuf/c/RZRCnOywdSk/m/s5QvifLCBgAJ

It seems like OpenCV and ONNX Runtime are both using protobuf with reflection. I don't think it can be disabled in either library.

**Comment by decahedron1** [comment]
Probably not, unless you can compile either OpenCV or ONNX Runtime to disable the problematic protobufs.

**Comment by TDiblik** [comment]
Hey, just heads-up, **this is no longer true**. I've managed to [get it working on both Linux and Windows](https://github.com/TDiblik/rust-ort-opencv-yolov8-example).
