### ISSUE TITLE
load-dynamic fails for build target x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by liob** [pykeio/ort#148]
Hi,

I tried to build ort with the cargo option "load-dynamic" for the build target x86_64-unknown-linux-musl. The build fails with a panic:

> downloaded binaries not available for target x86_64-unknown-linux-musl
> you may have to compile ONNX Runtime from source

It is my understanding, that the downloaded binaries should not be required when using the "load-dynamic" feature. Is this correct?

Kind regards

**Comment by decahedron1** [comment]
> It is my understanding, that the downloaded binaries should not be required when using the "load-dynamic" feature. Is this correct?

Not always. Enabling the CUDA feature downloads dynamic binaries for example.
