### ISSUE TITLE
The incorrect search path

### ISSUE THREAD

**Issue by rustui** [pykeio/ort#152]
I want to statically link onnxruntime for Android compilation on the Mac platform with ort, but I encountered an error saying:
"could not find native static library onnx"
I discovered that ort is searching for the path Android/_deps/onnx-build/Release, whereas onnx is actually located at Android/Release/_deps/onnx-build.

**Comment by rustui** [comment]
After I temporarily modified build.rs locally, it now reports an error that it cannot find re2. Indeed, I also cannot find libre2.a under the entire Android folder locally.

**Comment by decahedron1** [comment]
Can you run `git rev-parse HEAD` in the onnxruntime repo you checked out? This should've been fixed by #121 but I wonder if the dependencies/build process has changed since then.

**Comment by rustui** [comment]
The hash value is 2ac381c55397dffff327cc6efecf6f95a70f90a1

**Comment by decahedron1** [comment]
The question confuses me, but I think you might want the `load-dynamic` feature: https://ort.pyke.io/setup/linking#load-dynamic-a-glimmer-of-hope

**Comment by rustui** [comment]
Thank you for your reply. I found that I must first compile onnxruntime into a dynamic library (by adding the parameter --build_shared_lib) to avoid missing re2. After modifying build.rs, now ort can successfully statically link onnxruntime and run on Android.
