### ISSUE TITLE
undefined symbol: _ZSt28__throw_bad_array_new_lengthv when importing into wrapped rust code into python

### ISSUE THREAD

**Issue by patcollis34** [pykeio/ort#159]
I have some performance critical code that's written in rust and it wrapped with pyO3 and called from python. after building my rust library with ort = "2.0.0-alpha.4" installed, the python code throws this error(cpython-38-ImportError: x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv)  on startup. wondering if I'm missing something stupid with onnxruntime install. I am trying to run on linux with the default CPU execution provider

**Comment by decahedron1** [comment]
What distro & version?

**Comment by patcollis34** [comment]
<img width="670" alt="image" src="https://github.com/pykeio/ort/assets/7991125/23459109-17dc-4549-803e-5cde95115fb6">

**Comment by patcollis34** [comment]
<img width="639" alt="image" src="https://github.com/pykeio/ort/assets/7991125/cbfc418c-d86a-432d-8903-5674cea741ab">

**Comment by decahedron1** [comment]
Are you using a Conda environment?

**Comment by patcollis34** [comment]
I'm not using conda

**Comment by decahedron1** [comment]
https://stackoverflow.com/a/71368180/11589952
