### ISSUE TITLE
download-binaries name changes

### ISSUE THREAD

**Issue by gregszumel** [pykeio/ort#163]
I am upgrading a library package that uses ort (with default features). After updating to 2.0.0-rc.0 and running the library, I ran into this issue: 

'libonnxruntime.so.1.17.0: cannot open shared object file: No such file or directory\'

I checked the folder with our library binary, and there is a libonnxruntime.so file. However, older versions of ort were downloading/building an additional binary (e.g., libonnxruntime.so.1.14.1) which appears to be a renamed copy of the libonnxruntime.so file. 

In 2.0.0-rc, renaming the libonnxruntime.so to libonnxruntime.1.17.0 appears to fix the issue. It seems to me like to 2.0.0-rc.0 no longer does this renaming with default-features - is this expected, or am I doing something wrong?

**Comment by gregszumel** [comment]
I am also running with a few execution providers, relevant snippet of my `Cargo.toml` below:

```
[dependencies]
rustler = "0.29.0"
ort = { version = "2.0.0-rc.0" }
ndarray = "0.15.6"
half = "2.2.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
num-traits = "0.2.15"

[features]
# ONNXRuntime Execution providers
directml = ["ort/directml"]
coreml = ["ort/coreml"]
cuda = ["ort/cuda"]
tensorrt = ["ort/tensorrt"]
```

I am using Rustler (Elixir - Rust bridge package) to build my lib, and I'm not sure how it's downloading anything, since I don't see the `.so`'s when building it myself. I'm still investigating. 

It may help to download binarie - is it possible to download `libonnxruntime.so.1.17.0` using any features? Modifying my cargo to `ort = { version = "2.0.0-rc.0", features = ["download-binaries"]}` doesn't appear to download any in the `target/(debug/release)` directories

**Comment by decahedron1** [comment]
> It may help to download binaries - is it possible to download `libonnxruntime.so.1.17.0` using any features? Modifying my cargo to `ort = { version = "2.0.0-rc.0", features = ["download-binaries"]}` doesn't appear to download any in the `target/(debug/release)` directories

> I am using Rustler (Elixir - Rust bridge package) to build my lib, and I'm not sure how it's downloading anything, since I don't see the `.so`'s when building it myself. I'm still investigating.

`ort` will download static libraries without any EP features enabled, so there won't be anything in the target folder.

The only time dynamic binaries are downloaded is when `cuda` or `tensorrt` is enabled, and on Linux these binaries are originally versioned like `libonnxruntime.so.1.17.0`. The packaging code renames the versioned library to `libonnxruntime.so` in the final archive hence the error. A simple symlink should fix it.

**Comment by gregszumel** [comment]
Sounds great, thanks for your help!
