### ISSUE TITLE
Windows: Linking LNK4098

### ISSUE THREAD

**Issue by backkem** [pykeio/ort#179]
While trying to run the examples on Windows, I'm running into linker issues. At first the linker was unable to find `DXCORE.lib`. After installing the Windows SDK, this seems resolved. Now I get the following error:

```
warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
          onnxruntime.lib(utils.cc.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
          onnxruntime.lib(old.cc.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
          ...
          \examples\yolov8.exe : fatal error LNK1120: 19 unresolved externals
```

**Comment by decahedron1** [comment]
What version of Windows & Visual Studio?

**Comment by backkem** [comment]
Windows 11 23H2 Build 22631.3296
VS code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6)

**Comment by decahedron1** [comment]
The prebuilt binaries are compiled on Windows 11 with [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) 17.3. Try installing VS 17.3, but if that doesn't work, you'll probably have to build ONNX Runtime from source.
