### ISSUE TITLE
Error compiling with 2.0.0-rc.1

### ISSUE THREAD

**Issue by william-watson-swri** [pykeio/ort#186]
`OS`: Windows 11 version 23H2 build 22631.3296
`Cargo`/`rustc`: 1.73.0
`ort`: 2.0.0-rc.1

I'm trying to create a basic program using ORT following the instructions at https://ort.pyke.io/introduction. My `Cargo.toml` file is:
```toml
[package]
name = "abc"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "2.0.0-rc.1"
```
and my `main.rs` is:
```rust
use ort::{GraphOptimizationLevel, Session};

fn main() {
    let model = Session::builder()?
    .with_optimization_level(GraphOptimizationLevel::Level3)?
    .with_intra_threads(4)?;
    print!("Have model: {:?}", model);
}
```

However, this does not compile and I receive the following error when trying to do so:
```
error[E0445]: private trait `GetKernelAttribute` in public interface
  --> C:\Users\WWatson\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-2.0.0-rc.1\src\operator\kernel.rs:28:2
   |
28 |     pub fn get<T: GetKernelAttribute>(&self, name: impl AsRef<str>) -> Option<T> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private trait
...
34 | trait GetKernelAttribute {
   | ------------------------ `GetKernelAttribute` declared as private

For more information about this error, try `rustc --explain E0445`.
```

Using version 1.16.3 works, so that's what I'm going with now, but I'd like to use the most recent version if possible. I'm relatively new to Rust so any help would be appreciated!

**Comment by decahedron1** [comment]
It seems like this behavior changed between Rust versions; updating Rust to 1.76 or using https://github.com/pykeio/ort/commit/681da43965eb9a7bbce06cea1a94b1a1497686a9 will fix it.
