### ISSUE TITLE
Request for new RC release to crates.io

### ISSUE THREAD

**Issue by messense** [pykeio/ort#190]
Hello, can you release a new 2.0.0 RC version to crates.io so it's easier to lookup APIs on docs.rs? Thanks!

**Comment by decahedron1** [comment]
I'd like to get #75 & #184 sorted out before a new rc release.
In the meantime, I've uploaded docs from `main` here: https://spaces.pyke.io/ort-api/ort/

**Comment by decahedron1** [comment]
https://crates.io/crates/ort/2.0.0-rc.2
