### ISSUE TITLE
WASM: `External initializers are not enabled in this build`

### ISSUE THREAD

**Issue by decahedron1** [pykeio/ort#192]
Hi
@decahedron1 

Build and load of wasm module in the browser is successful.

But when inferencing the model, I face following error:

```
panicked at libtashkeel-wasm\src\lib.rs:23:34:
called `Result::unwrap()` on an `Err` value: InferenceError("Failed to run model using onnxruntime via ort. Caused by Failed to create ONNX Runtime session: Deserialize tensor attn_layers.0.ccm.layernorm.bias failed.External initializers are not enabled in this build
```

I'm using an `ort` model.

_Originally posted by @mush42 in https://github.com/pykeio/ort/issues/75#issuecomment-2081213832_

**Comment by decahedron1** [comment]
@mush42 Are you able to upload the converted `.ort` model?

**Comment by decahedron1** [comment]
Should be fixed by https://github.com/pykeio/ort/commit/80be2068296b04e8ae0a442d4b9c2d635362d07e

**Comment by mush42** [comment]
@decahedron1 
Here's the model. It is a quantized model using `neural compressor`.
[model.zip](https://github.com/pykeio/ort/files/15141969/model.zip)

**Comment by decahedron1** [comment]
Can you confirm that https://github.com/pykeio/ort/commit/80be2068296b04e8ae0a442d4b9c2d635362d07e fixed this issue by setting `ort` as a git dependency:
```toml
[dependencies]
ort = { git = "https://github.com/pykeio/ort.git", rev = "80be2068296b04e8ae0a442d4b9c2d635362d07e" }
```

**Comment by mush42** [comment]
@decahedron1  I confirm that #80be2068296b04e8ae0a442d4b9c2d635362d07e fixes the issue.

**Comment by mush42** [comment]
@decahedron1 
If possible, make a new rc release.

**Comment by mush42** [comment]
My model is now live at:
https://mush42.github.io/libtashkeel/

**Comment by mush42** [comment]
Do you have any idea of what has been added to nightly to make ort work in wasm-unknown-unknown?

Just came by this:
https://github.com/Liamolucko/find_wasm_import

**Comment by decahedron1** [comment]
No idea. My best guesses are https://github.com/rust-lang/rust/pull/124036 or the LLVM 18 upgrade (which should land in v1.78 stable, releasing tomorrow).

**Comment by mush42** [comment]
OK.

Whatever it is, it seams to add around 5-6 MB to the `.wasm` module bundle.

Using stable, my build is around 6 MB when compiled with stable, jumped to 12 MB when compiled with nightly.
