### ISSUE TITLE
Metadata returns wrong info

### ISSUE THREAD

**Issue by jamjamjon** [pykeio/ort#193]
### Description
Method provided by `session.metadata()` can not return the right data:  `meta.name()`, `meta.version()`. 

### Model
![image](https://github.com/pykeio/ort/assets/51357717/3727e05f-52be-46aa-ac28-c1faa56e1b60)

### Code
```Rust
    let session = Session::builder()?.commit_from_file(path)?;

    let meta = session.metadata()?;
    if let Ok(x) = meta.name() {
        println!("Name: {x}");
    }
    if let Ok(x) = meta.description() {
        println!("Description: {x}");
    }
    if let Ok(x) = meta.producer() {
        println!("Produced by {x}");
    }
    if let Ok(x) = meta.version() {
        println!("version: {x}");
    }
```

### Result
```shell
Name: torch_jit
Description:
Produced by pytorch
version: 9223372036854775807
```

### Question
How to get the `opset_import`,  `ir_version`, `producer_version` from the [ModelProto](https://onnx.ai/onnx/api/classes.html#modelproto) like `Python` code with `onnx`.

```Python
import onnx 
from onnx import __version__, IR_VERSION

model = onnx.load("model.onnx")
print(model.producer_name)
print(model.producer_version)
print(model.doc_string)
print(model.ir_version)
print(model.opset_import)
print(__version__)
print(IR_VERSION)
print(onnx.defs.onnx_opset_version())
```

**Comment by decahedron1** [comment]
`meta.name()` is correct. `meta.version()` returning `i64::MAX` seems to indicate that the model's version field is not set - [Netron defaults the version to `0`](https://github.com/lutzroeder/netron/blob/83f42349427f477a82118cbf730f0af2eb9b6b2c/source/onnx-proto.js#L529).

> How to get the `opset_import`, `ir_version`, `producer_version` from the [ModelProto](https://onnx.ai/onnx/api/classes.html#modelproto) like Python code with `onnx`.

ONNX Runtime doesn't expose APIs for these fields, so there's no way to do that with `ort`.

**Comment by jamjamjon** [comment]
Thanks!
