### ISSUE TITLE
wasm32-unknown-unknown - .ort model weights not supported

### ISSUE THREAD

**Issue by mosure** [pykeio/ort#194]
when building a session with target `wasm32-unknown-unknown`, via:
```rust
static ORT_DATA: &[u8] = include_bytes!("model.ort");

...
Session::builder()
    .unwrap()
    .commit_from_memory_directly(ORT_DATA)
    .unwrap()
```

a runtime error is thrown:
`Deserialize tensor 'weights' failed. External initializers are not enabled in this build.`

this occurs when an `.ort` model contains 'internal tensors'

**Comment by mosure** [comment]
here is an example `.ort` file: https://github.com/mosure/bevy_flame/blob/main/assets/models/flame.ort

**Comment by decahedron1** [comment]
Sorry, this was fixed by https://github.com/pykeio/ort/commit/80be2068296b04e8ae0a442d4b9c2d635362d07e, but I'm waiting to push a new rc release.
