### ISSUE TITLE
error while loading shared libraries: libonnxruntime.so.1.17.3

### ISSUE THREAD

**Issue by galenoshea** [pykeio/ort#196]
I'm running ort = "=2.0.0-rc.2" and can build the project but when I try to run the executable I get error:
`target/release/rust_ort: error while loading shared libraries: libonnxruntime.so.1.17.3: cannot open shared object file: No such file or directory`

**Comment by decahedron1** [comment]
If you enabled `cuda`/`tensorrt` or `load-dynamic`, onnxruntime will be dynamically linked, which occasionally requires some additional configuration. See the notes on setting up dynamic linking here: https://ort.pyke.io/setup/linking#dynamic-linking

**Comment by galenoshea** [comment]
thanks for the blazingly fast reply! Enabling `load-dynamic` worked without pointing ort to the dylib.
