### ISSUE TITLE
directorml12 err

### ISSUE THREAD

**Issue by redoriental** [pykeio/ort#205]
use ort 2.0.0.rc2.The same model, the same input, when I use CPU, it can run normally, but when I use directorml12, it reports an error -》thread 'main' panicked at src\main.rs:83:130:
called `Result::unwrap()` on an `Err` value: SessionRun(Msg("Non-zero status code returned while running Resize node. Name:'/flownet/block0_1/Resize_1' Status Message: "))
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\result.rs:1654
   3: <image::codecs::openexr::OpenExrDecoder<R> as image::image::ImageDecoder>::read_image_boxed
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\untitled5.exe` (exit code: 101)  My computer supports directorml12
And I also used directorml for GPU acceleration on onnxruntime in Python, but there was no problem

**Comment by decahedron1** [comment]
Can't reproduce here with the `modnet` example, which also contains a Resize node. This is a problem with ONNX Runtime or your model - maybe you have a different version of `onnxruntime` installed for Python?

**Comment by redoriental** [comment]
The onnxruntime version I installed in Python is 1.18.0，And I didn't report any errors when using the ort CPU, so it shouldn't be a problem with my model

**Comment by decahedron1** [comment]
The `onnxruntime-directml` Python package ships with a newer version of DirectML, whereas ONNX Runtime via `ort` is likely using the DirectML runtime that ships with Windows, which is often older. Try putting the `DirectML.dll` from that package (or [from Nuget](https://www.nuget.org/packages/Microsoft.AI.DirectML/1.13.1)) in your PATH so it can be picked up by ONNX Runtime.
