### ISSUE TITLE
How to use I/O bindings in 2.0.x

### ISSUE THREAD

**Issue by lorenzomammana** [pykeio/ort#209]
We are not able to understand how to run a model using io bindings, the documentation page is empty https://ort.pyke.io/perf/io-binding

In https://ort.pyke.io/migrating/v2 it's stated "You can also supply ort::inputs! your IoBinding by specifying bind =:"
```
let binding = model.create_binding()?;
...
let outputs = model.run(ort::inputs![bind = binding]?)?;
```

But this macro doesn't seem to work, can we get a more detailed explanation on how to use io bindings please?

**Comment by lorenzomammana** [comment]
@decahedron1 Is this feature supported? It would be quite important for performance

**Comment by decahedron1** [comment]
https://docs.rs/ort/2.0.0-rc.2/ort/struct.IoBinding.html

`IoBinding` has been supported since 1.15, I am working on documentation & an example demonstrating its usage.

**Comment by lorenzomammana** [comment]
Nice, yes we saw the API documentation, yet we can't fully figure out how to use it properly 😅

**Comment by decahedron1** [comment]
[2.0.0-rc.3](https://github.com/pykeio/ort/releases/tag/v2.0.0-rc.3) changed the API slightly and [now includes some documentation and an example](https://docs.rs/ort/2.0.0-rc.3/ort/struct.IoBinding.html).
