### ISSUE TITLE
AMD MIGraphX Support

### ISSUE THREAD

**Issue by phudtran** [pykeio/ort#212]
Would love to have AMD MIGraphX support. There is currently an open PR for Windows support over on the ONNX runtime repo.

https://github.com/microsoft/onnxruntime/pull/21084#issuecomment-2179952511

**Comment by decahedron1** [comment]
Added in https://github.com/pykeio/ort/commit/19d66de302fa7bfc065555fec3815e81c6d7e28e, please let me know if it works without issue.
