### ISSUE TITLE
WASM fails on rc3 with encoding issue

### ISSUE THREAD

**Issue by smallbraingames** [pykeio/ort#230]
Running wasm examples that were working with ```ort = { git = "https://github.com/pykeio/ort.git", rev = "80be2068296b04e8ae0a442d4b9c2d635362d07e" }``` do not work anymore on latest main (rc3), specifically failing with error

```
TypeError: The encoded data was not valid for encoding utf-8
    at TextDecoder.decode (node:internal/encoding:443:16)
...
```

**Comment by decahedron1** [comment]
What does `rustc --version` say? And are you able to provide a minimal reproduction?

**Comment by smallbraingames** [comment]
> What does `rustc --version` say? And are you able to provide a minimal reproduction?

rustc 1.79.0 (129f3b996 2024-06-10)


I'll provide the repro soon

**Comment by decahedron1** [comment]
Thanks - could you also try 1.76.0 and see if anything changes?
