### ISSUE TITLE
TensorRTExecutionProvider: Attempt to use DefaultLogger but none has been registered

### ISSUE THREAD

**Issue by zopieux** [pykeio/ort#236]
It looks like the default setup for `TensorRTExecutionProvider` is not working as of latest release candidate. This seems to be a compile-time issue, a default logger is not registered at init time. This doesn't seem like something I can influence as `ort` library user.

```
Failed to register TensorRT!
Err(ExecutionProvider(Msg("/home/runner/work/ort-artifacts-staging/ort-artifacts-staging/onnxruntime/include/onnxruntime/core/common/logging/logging.h:320
static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger()
Attempt to use DefaultLogger but none has been registered.\n")))
```

https://www.sidefx.com/docs/hdk/onnxruntime_2core_2common_2logging_2logging_8h_source.html

```rust
// main.rs
let builder = Session::builder()?;
let tensorrt = TensorRTExecutionProvider::default();
let reg = tensorrt.register(&builder);
if reg.is_err() {
  eprintln!("Failed to register TensorRT! {reg:?}");
  std::process::exit(1);
}
```

Ran in Docker image `nvcr.io/nvidia/tensorrt:24.06-py3` which should provide all the necessary libraries.

**Comment by decahedron1** [comment]
Runing `ort::init().commit()?;` at the top of `main.rs`, before creating the `TensorRTExecutionProvider`, should fix this.

**Comment by zopieux** [comment]
Thanks for the quick reply! Confirmed working with the added `init`.

Nit: I don't think this was documented, but I should have looked more closely at some other examples where this is being used.
