### ISSUE TITLE
Hot swapping weights for certain layers

### ISSUE THREAD

**Issue by cyanic-selkie** [pykeio/ort#242]
Hi. I have a use case where I want to load an LLM base model with several LoRA variants fine-tuned to do different things. So, the workflow would be, load one set of LoRA weights, do some inference, replace them with another set of LoRA weights, do some inference, and so on. The base model can have the randomly initialized LoRA layers, so no changes to the graph are needed, only the weights have to change.

I obviously don't want to create a new session every time, but rather keep the loaded weights in memory. From what I understand from other `onnx` related threads, this can be done with `AddInitializers` functionality.

Looking at the docs, this library only supports setting the additional initializers when creating the session, but not later. Is there a way to do what I am asking with this library directly? I suppose I could extract the functionality from the `with_model_from_file_and_external_initializers` method. Would this work? Is there a possibility of exposing this functionality to the public API?

**Comment by decahedron1** [comment]
Configuring external initializers after session creation isn't supported by ONNX Runtime.
