### ISSUE TITLE
RC4 failed on i686 build

### ISSUE THREAD

**Issue by ycclnn** [pykeio/ort#245]
I am new to Rust lang and ort and follow the dynamic loading onnxruntime tutorial. But I got this problem when building my project with Config.toml:
`
[package]
publish = false
name = "embed"
version = "0.0.1"
edition = "2021"
[[bin]]
name = "embed"
path = "src/embedding.rs"

[dependencies]
ort = { version = "2.0.0-rc.2", features = ["load-dynamic"] }
ndarray = "0.15"
tokenizers = { version = ">=0.13.4", default-features = false, features = [ "onig" ] }
tracing-subscriber = { version = "0.3", default-features = false, features = [ "env-filter", "fmt" ] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }

#
#[features]
#load-dynamic = [ "ort/load-dynamic" ]

`

`
cargo build --release --target i686-pc-windows-msvc
   Compiling mime_guess v2.0.5
   Compiling ort-sys v2.0.0-rc.4
   Compiling num-integer v0.1.46
   Compiling num-complex v0.4.6
   Compiling itertools v0.11.0
   Compiling http-body v0.4.6
   Compiling headers-core v0.2.0
   Compiling futures-channel v0.3.30
   Compiling pin-project-internal v1.1.5
   Compiling monostate-impl v0.1.13
   Compiling encoding_rs v0.8.34
   Compiling bitflags v1.3.2
error: failed to run custom build command for `ort-sys v2.0.0-rc.4`                                                                            

Caused by:
  process didn't exit successfully: `C:\Users\47026\Documents\onnx\target\release\build\ort-sys-7a5b486d0463237f\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBONNXRUNTIME_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_i686-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_i686_pc_windows_msvc
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_i686-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_i686_pc_windows_msvc
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_i686-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_i686_pc_windows_msvc
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  onnxruntime not found using pkg-config, falling back to manual setup.
  cargo:rerun-if-env-changed=ORT_LIB_LOCATION
  cargo:rerun-if-env-changed=ORT_LIB_PROFILE
  selected feature set: none

  --- stderr
  thread 'main' panicked at C:\Users\47026\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-sys-2.0.0-rc.4\build.rs:381:17:
  downloaded binaries not available for target i686-pc-windows-msvc
  you may have to compile ONNX Runtime from source
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

`

**Comment by decahedron1** [comment]
> downloaded binaries not available for target i686-pc-windows-msvc
> you may have to compile ONNX Runtime from source

https://ort.pyke.io/setup/linking

**Comment by ycclnn** [comment]
> > you may have to compile ONNX Runtime from source

Yeah I read this page very carefully. I would like to build the project for win/mac/linux and provide embedding service. Since I configure it to be "load-dynamic", why the build process mention I need to compile it from source? I assume I'd be able to use ORT_LIB_DYLIB at the same time I start the service.

**Comment by decahedron1** [comment]
> Since I configure it to be "load-dynamic", why the build process mention I need to compile it from source?

The `download-binaries` feature is enabled by default, and it will attempt to download binaries even if `load-dynamic` is also enabled. The build should succeed without issue if you set `default-features = false` for the ort dependency.

**Comment by ycclnn** [comment]
> > Since I configure it to be "load-dynamic", why the build process mention I need to compile it from source?
> 
> The `download-binaries` feature is enabled by default, and it will attempt to download binaries even if `load-dynamic` is also enabled. The build should succeed without issue if you set `default-features = false` for the ort dependency.

Thanks. I will try it.

**Comment by ycclnn** [comment]
Hi, sorry to bother again and I know this is kinda unrelated to ort: so far I managed to build mac and win. But couldn't successfully build linux-musl. Tried several docker image and use both strategy mentioned in your doc. 
1. static linking the ![IMG_1841](https://github.com/user-attachments/assets/c149a8f4-802e-479e-a035-68478597c4d4)
https://github.com/csukuangfj/onnxruntime-libs/releases by removing the load-dynamic feature. Output be like:
2. use dynamic loading with load-dynamic feature turned on. Build can be finished but when I ran the binary, output be like:
`
Dynamic loading not supported
`
Could you point me on the right track? Wouldn't be more thankful

**Comment by ycclnn** [comment]
```
[package]
publish = false
name = "embed"
version = "0.0.1"
edition = "2021"
[[bin]]
name = "embed"
path = "src/embedding.rs"

[dependencies]
ort = { version = "1.16.3", default-features = false }
ndarray = "0.15"
tokenizers = { version = ">=0.13.4", default-features = false, features = [ "onig" ] }
tracing-subscriber = { version = "0.3", default-features = false, features = [ "env-filter", "fmt" ] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
```

```
use std::convert::Infallible;
use std::sync::Arc;
use serde::{Deserialize, Serialize};
use warp::Filter;
use clap::Parser;
use std::fs::OpenOptions;
use std::io::Write;

use std::path::Path;
use ndarray::{Array2, Axis, Ix2};
use ort::{GraphOptimizationLevel, Session};
use tokenizers::Tokenizer;
use tokio::sync::Mutex;

#[derive(Deserialize)]
struct EmbeddingRequest {
    model: String,
    prompt: String,
}

#[derive(Serialize)]
struct EmbeddingResponse {
    embedding: Vec<f32>,
}

struct AppState {
    session: Session,
    tokenizer: Tokenizer,
}

#[derive(Parser, Debug)]
#[command(name = "Embedding Server")]
#[command(about = "A server that returns text embeddings.", long_about = None)]
struct Args {
    /// Port to run the server on
    #[arg(short, long, default_value_t = 3030)]
    port: u16,

    /// Path to the model file
    #[arg(short, long)]
    model: String,

    /// Path to the tokenizer file
    #[arg(short, long)]
    tokenizer: String,

    /// Path to the ONNX Runtime dynamic library
    #[arg(short, long)]
    dylib: String,
}

#[tokio::main]
async fn main() {
    // Parse command line arguments
    let args = Args::parse();
    //     let dylib_path = "../";
    // Initialize tracing to receive debug messages from `ort`
    tracing_subscriber::fmt::init();
    ort::init().commit().unwrap();
    //     ort::init()
    //         .with_name("sbert")
    //         .commit()
    //         .unwrap();

    // Load our model
    let session = Session::builder()
        .unwrap()
        .with_optimization_level(GraphOptimizationLevel::Level1)
        .unwrap()
        .with_intra_threads(1)
        .unwrap()
        .commit_from_file(&args.model)
        .unwrap();

    // Load the tokenizer
    let tokenizer = Tokenizer::from_file(Path::new(&args.tokenizer)).unwrap();

    let state = Arc::new(Mutex::new(AppState { session, tokenizer }));

    let api = warp::path("api")
        .and(warp::path("embeddings"))
        .and(warp::post())
        .and(warp::body::json())
        .and(with_state(state.clone()))
        .and_then(handle_embeddings);

    let routes = warp::serve(api).run(([127, 0, 0, 1], args.port));

    println!("Server running on http://127.0.0.1:{}", args.port);

    routes.await;
}

fn with_state(
    state: Arc<Mutex<AppState>>,
) -> impl Filter<Extract = (Arc<Mutex<AppState>>,), Error = Infallible> + Clone {
    warp::any().map(move || state.clone())
}

async fn handle_embeddings(
    body: EmbeddingRequest,
    state: Arc<Mutex<AppState>>,
) -> Result<impl warp::Reply, Infallible> {
    let state = state.lock().await;
    let inputs = vec![body.prompt.as_str()];

    // Encode our input strings. `encode_batch` will pad each input to be the same length.
    let encodings = state.tokenizer.encode_batch(inputs.clone(), false).unwrap();

    // Get the padded length of each encoding.
    let padded_token_length = encodings[0].len();

    // Get our token IDs & mask as a flattened array.
    let ids: Vec<i64> = encodings.iter().flat_map(|e| e.get_ids().iter().map(|i| *i as i64)).collect();
    let mask: Vec<i64> = encodings.iter().flat_map(|e| e.get_attention_mask().iter().map(|i| *i as i64)).collect();

    // Convert our flattened arrays into 2-dimensional tensors of shape [N, L].
    let a_ids = Array2::from_shape_vec([inputs.len(), padded_token_length], ids).unwrap();
    let a_mask = Array2::from_shape_vec([inputs.len(), padded_token_length], mask).unwrap();

    // Run the model.
    let outputs = state.session.run(ort::inputs![a_ids, a_mask].unwrap()).unwrap();

    // Extract our embeddings tensor and convert it to a strongly-typed 2-dimensional array.
    let embeddings = outputs[1].try_extract_tensor::<f32>().unwrap().into_dimensionality::<Ix2>().unwrap();

    let response = EmbeddingResponse {
        embedding: embeddings.row(0).to_vec(),
    };

    Ok(warp::reply::json(&response))
}


```
