### ISSUE TITLE
Equivalent for OrtOwnedTensor in ort 2.0

### ISSUE THREAD

**Issue by altunenes** [pykeio/ort#247]
Hello and thank you for the ort! I noticed that `OrtOwnedTensor ` is no longer available in version 2.0. I searched through the migration guide [here](https://ort.pyke.io/migrating/v2) but couldn't find any information about its equivalent in the new version.

Could you please clarify what the equivalent of OrtOwnedTensor is in ort 2.0, or provide guidance on how to achieve similar functionality with the new API?

Thank you for your help!

**Comment by decahedron1** [comment]
The equivalent would be [`ort::Tensor`](https://docs.rs/ort/2.0.0-rc.4/ort/type.Tensor.html).

Admittedly, the migration docs are a bit out of date, so I'd suggest also taking a look at the [examples](https://github.com/pykeio/ort/tree/main/examples) (& [on `1.16` branch](https://github.com/pykeio/ort/tree/1.16/examples)) to see how usage has changed.

**Comment by altunenes** [comment]
thank you so much!
