### ISSUE TITLE
Link msvc in debug mode

### ISSUE THREAD

**Issue by thewh1teagle** [pykeio/ort#255]
First of all thanks for this library. really love it.

When I compile project that uses both `ort` and [`knf-rs`](https://github.com/thewh1teagle/knf-rs) the compile failed with the following error:

```console
= note: libort_sys-6af98614ea6a6726.rlib(onnxruntime_c_api.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in libknf_rs_sys-657516f9843f65bb.rlib(knfc.obj)
```
Looks like `ort` is always linking MSVC release mode even on debug build.

**Comment by decahedron1** [comment]
You'll have to compile ONNX Runtime from source.
