### ISSUE TITLE
Link msvc dynamic

### ISSUE THREAD

**Issue by thewh1teagle** [pykeio/ort#259]
Currently, ort links msvc statically, which isn't standard in Rust and introduces conflicts for me, for example with whisper.cpp. Could you please link it dynamically instead?

Thanks!

Discussion in Discord: https://discord.com/channels/1029216970027049072/1272356863144493057

**Comment by decahedron1** [comment]
Fixed in https://github.com/pykeio/ort/commit/ab293f89a2e5321c5ba4998080fed6a84943e5ad
