### ISSUE TITLE
libonnxruntime.so.1 not found on rc5

### ISSUE THREAD

**Issue by JanFontanet** [pykeio/ort#269]
I've updated to the latest rc and I found this issue:
`error while loading shared libraries: libonnxruntime.so.1: cannot open shared object file: No such file or directory`

In the target directory I found symbolic links with the names `libonnxruntime.so` and` libonnxruntime.so.1.19`, so I just created another identical symbolic link but with the` libonnxruntime.so.1` name and everything works.

**Comment by decahedron1** [comment]
Implemented a fix for future versions. For rc5, creating the symlink manually will work just fine.
