### ISSUE TITLE
windows cuda build  failed

### ISSUE THREAD

**Issue by NoNameCanUse9** [pykeio/ort#279]
i cloned this repo， and  try to build the yolov8 demo with cuda. I already I have added cuda and cudnn in to the path. Like this 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\  C:\software\cudnn\cudnn-windows-x86_64-9.0.0.312_cuda12-archive\bin
But  The terminal printed these errors:
 libort_sys-9b733ff55f5888d3.rlib(svmclassifier.obj) : error LNK2019:  unresolved external symbol __std_max_element_f，函数 "float * __cdecl std::_Max_element_vectorized<float>(float * const,float * const)" (??$_Max_element_vectorized@M@std@@YAPEAMQEAM0@Z) 中引用了该符号
          libort_sys-9b733ff55f5888d3.rlib(logits_processor.obj) : error LNK2001:  unresolved external symbol __std_max_element_f
          libort_sys-9b733ff55f5888d3.rlib(beam_search_scorer.obj) : error LNK2001:  unresolved external symbol __std_max_element_f
          libort_sys-9b733ff55f5888d3.rlib(bias_softmax_fusion.obj) : error LNK2019:  unresolved external symbol__std_max_4i，函数 "auto __cdecl std::_Max_vectorized<int const >(int const * const,int const * const)" (??$_Max_vectorized@$$CBH@std@@YA?A_PQEBH0@Z) 中引用了该符号
          libort_sys-9b733ff55f5888d3.rlib(PooledUploadHeap.obj) : error LNK2019:  unresolved external symbol__std_max_8u，函数 "auto __cdecl std::_Max_vectorized<unsigned __int64 const >(unsigned __int64 const * const,unsigned __int64 const * const)" (??$_Max_vectorized@$$CB_K@std@@YA?A_PQEB_K0@Z) 中引用了该 符号
          libort_sys-9b733ff55f5888d3.rlib(DmlOperatorScatter.obj) : error LNK2001:  unresolved external symbol __std_max_8u
          libort_sys-9b733ff55f5888d3.rlib(DmlOperatorGather.obj) : error LNK2001:  unresolved external symbol __std_max_8u
          C:\study\rust\ort\target\debug\examples\yolov8.exe : fatal error LNK1120: 5 个 unresolved external symbol。
Did i do something wrong？ I need some help。

**Comment by decahedron1** [comment]
Make sure you have an up-to-date version of Visual Studio 2022 (>= 17.11).

**Comment by NoNameCanUse9** [comment]
it works， Thanks！
