### ISSUE TITLE
Linkage failure for MacOSX ARM64

### ISSUE THREAD

**Issue by cyanic-selkie** [pykeio/ort#285]
Hi,

I am trying to statically link the onnxruntime library as per the instructions on in the documentation.  I cloned the onnxruntime repo, and successfully built using the following command:
`./build.sh --config Release --parallel --compile_no_warning_as_error --skip_submodule_sync --use_xcode`

This is my dependency:
`ort = { version = "2.0.0-rc.6", features = ["ndarray"], default-features = false }`

This is my build command:
`ORT_LIB_LOCATION=/path/to/onnxruntime/build/MacOS/Release cargo build`

I get the following linker error:

> Undefined symbols for architecture arm64:
            "absl::log_internal::LogMessage::OstreamView::stream()", referenced from:
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::InstOp, 0>(re2::InstOp const&) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RegexpOp, 0>(re2::RegexpOp const&) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Options::Encoding, 0>(re2::RE2::Options::Encoding const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Anchor, 0>(re2::RE2::Anchor const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, 0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* const&) in libort_sys-748c5b75d275d089.rlib[628](tostring.o)
            "absl::log_internal::LogMessage::OstreamView::OstreamView(absl::log_internal::LogMessage::LogMessageData&)", referenced from:
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::InstOp, 0>(re2::InstOp const&) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RegexpOp, 0>(re2::RegexpOp const&) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Options::Encoding, 0>(re2::RE2::Options::Encoding const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Anchor, 0>(re2::RE2::Anchor const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, 0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* const&) in libort_sys-748c5b75d275d089.rlib[628](tostring.o)
            "absl::log_internal::LogMessage::OstreamView::~OstreamView()", referenced from:
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::InstOp, 0>(re2::InstOp const&) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::InstOp, 0>(re2::InstOp const&) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::InstOp, 0>(re2::InstOp const&) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RegexpOp, 0>(re2::RegexpOp const&) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RegexpOp, 0>(re2::RegexpOp const&) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RegexpOp, 0>(re2::RegexpOp const&) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Options::Encoding, 0>(re2::RE2::Options::Encoding const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Options::Encoding, 0>(re2::RE2::Options::Encoding const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<re2::RE2::Options::Encoding, 0>(re2::RE2::Options::Encoding const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                ...
            "void absl::log_internal::LogMessage::CopyToEncodedBuffer<(absl::log_internal::LogMessage::StringType)0>(std::__1::basic_string_view<char, std::__1::char_traits<char>>)", referenced from:
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::TrySearch(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::Compiler::FindByteRange(int, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Compiler::Copy(re2::Frag) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                ...
            "absl::log_internal::LogMessage::LogMessage(char const*, int, absl::log_internal::LogMessage::ErrorTag)", referenced from:
                re2::RE2::Init(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Options const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Init(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Options const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Options::ParseFlags() const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::DoMatch(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Anchor, unsigned long*, re2::RE2::Arg const* const*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                ...
            "absl::log_internal::LogMessage::LogMessage(char const*, int, absl::LogSeverity)", referenced from:
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::TrySearch(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::Compiler::FindByteRange(int, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Compiler::Copy(re2::Frag) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Compiler::PostVisit(re2::Regexp*, re2::Frag, re2::Frag, re2::Frag*, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Compiler::PostVisit(re2::Regexp*, re2::Frag, re2::Frag, re2::Frag*, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Regexp::Walker<re2::Frag>::Reset() in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                ...
            "absl::log_internal::LogMessage::~LogMessage()", referenced from:
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::TrySearch(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::TrySearch(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::TrySearch(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::Compiler::FindByteRange(int, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                re2::Compiler::FindByteRange(int, int) in libort_sys-748c5b75d275d089.rlib[613](compile.o)
                ...
            "absl::log_internal::LogMessage::operator<<(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
                re2::FactorAlternationImpl::Round3(re2::Regexp**, int, re2::Regexp::ParseFlags, std::__1::vector<re2::Splice, std::__1::allocator<re2::Splice>>*) in libort_sys-748c5b75d275d089.rlib[619](parse.o)
                re2::RE2::Init(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Options const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Init(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Options const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Init(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Options const&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::DoMatch(std::__1::basic_string_view<char, std::__1::char_traits<char>>, re2::RE2::Anchor, unsigned long*, re2::RE2::Arg const* const*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                void absl::base_internal::CallOnceImpl<re2::RE2::ReverseProg() const::$_0, re2::RE2 const*>(std::__1::atomic<unsigned int>*, absl::base_internal::SchedulingMode, re2::RE2::ReverseProg() const::$_0&&, re2::RE2 const*&&) in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                ...
            "absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<unsigned char, 0>(unsigned char const&)", referenced from:
                re2::Regexp::ComputeSimple() in libort_sys-748c5b75d275d089.rlib[627](simplify.o)
            "absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<int, 0>(int const&)", referenced from:
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::BitState::Push(int, char const*) in libort_sys-748c5b75d275d089.rlib[612](bitstate.o)
                re2::NFA::Search(std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, bool, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) in libort_sys-748c5b75d275d089.rlib[617](nfa.o)
                re2::Regexp::RemoveLeadingString(re2::Regexp*, int) in libort_sys-748c5b75d275d089.rlib[619](parse.o)
                re2::Regexp::FactorAlternation(re2::Regexp**, int, re2::Regexp::ParseFlags) in libort_sys-748c5b75d275d089.rlib[619](parse.o)
                re2::Regexp::FactorAlternation(re2::Regexp**, int, re2::Regexp::ParseFlags) in libort_sys-748c5b75d275d089.rlib[619](parse.o)
                re2::UnHex(int) in libort_sys-748c5b75d275d089.rlib[619](parse.o)
                ...
            "absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<unsigned long, 0>(unsigned long const&)", referenced from:
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                re2::RE2::Match(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long, unsigned long, re2::RE2::Anchor, std::__1::basic_string_view<char, std::__1::char_traits<char>>*, int) const in libort_sys-748c5b75d275d089.rlib[624](re2.o)
                ...
            "absl::log_internal::LogMessage& absl::log_internal::LogMessage::operator<<<unsigned short, 0>(unsigned short const&)", referenced from:
                re2::Regexp::Destroy() in libort_sys-748c5b75d275d089.rlib[625](regexp.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

It seems that abseil isn't being linked correctly. This happens for both the master branch and the v1.19.2 tag of onnxruntime. Is there another step that I am missing?

**Comment by jawj** [comment]
I'm seeing something similar. Will there be a new RC (or final) release with this fix in soon?

**Comment by decahedron1** [comment]
@jawj Just released [`2.0.0-rc.7`](https://crates.io/crates/ort/2.0.0-rc.7) with the fix, sorry for the wait!
