### ISSUE TITLE
download-binaries in 2.0.0-rc.6

### ISSUE THREAD

**Issue by bedapisl** [pykeio/ort#290]
Hello,
the `download-binaries` is not working for me. I have this in my Cargo.toml:

```
[dependencies.ort]
version = "2.0.0-rc.6"
default-features = false
features = ["download-binaries", "copy-dylibs", "load-dynamic"]
```

but I am getting runtime error: 
```
thread ... panicked at /home/beda/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.6/src/lib.rs:130:33:
An error occurred while attempting to load the ONNX Runtime binary at `libonnxruntime.so`: libonnxruntime.so: cannot open shared object file: No such file or directory
```

I have done some debugging of the build script and found that `libonnxruntime.a` is downloaded but I don't see `libonnxruntime.so` anywhere:
```
beda@notebook:lib$ pwd
/home/beda/.cache/ort.pyke.io/dfbin/x86_64-unknown-linux-gnu/C718EFE9677E093BCD986A27EBE83BDDD0DAFD6967FAFB0DE311A239D27F4A71/onnxruntime/lib
beda@notebook:lib$ ls
libonnxruntime.a
```

I am upgrading from version 1.16.3. That version worked without any problems. Am I doing something wrong? Was there some change in the downloading?

**Comment by decahedron1** [comment]
Remove the `load-dynamic` feature unless you're also using CUDA or TensorRT or a custom build that uses dylibs. The default (CPU) build is statically linked, and `load-dynamic` configures `ort` to not link at all.

**Comment by bedapisl** [comment]
Thanks for the fast answer, it works.
