### ISSUE TITLE
Mismatched Protocol Buffer versions (runtime vs installed)

### ISSUE THREAD

**Issue by zopieux** [pykeio/ort#292]
Hello there,

I was using 2.0.0-rc4 which was working fine. I needed to upgrade nalgebra though, so it turns I needed to upgrade ort. Using 2.0.0-rc6, everything compiles just fine, however upon running the binary, I get this:

```
[libprotobuf FATAL /home/runner/work/ort-artifacts-staging/ort-artifacts-staging/onnxruntime/build/_deps/protobuf-src/src/google/protobuf/stubs/common.cc:83]
This program was compiled against version 3.12.4 of the Protocol Buffer runtime library,
which is not compatible with the installed version (3.21.12).  
Contact the program author for an update.  If you compiled the program yourself,
make sure that your headers are from the same version of Protocol Buffers as your link-time library.
(Version verification failed in "./obj-x86_64-linux-gnu/modules/dnn/versions.pb.cc".)

terminate called after throwing an instance of 'google::protobuf::FatalException'
```

I suppose this is because I am using the distributed binaries (`download-binaries` feature is enabled). Can this be fixed somehow? FYI, the environment in question is the `pytorch/pytorch:2.4.1-cuda12.1-cudnn9-runtime` Docker image.

**Comment by decahedron1** [comment]
What other crates does your application depend on? I'm wondering if there is another crate that depends on protobuf (like OpenCV) that ends up getting the wrong library. (Though if that were the case, I'd expect it to not link due to duplicate symbols...)

**Comment by zopieux** [comment]
Oh, right, there's a lot going on here, and that includes opencv indeed. Thanks for your quick reply, I'll have to root-cause this further. Rust dependency hell at it again :sweat:

**Comment by solaoi** [comment]
Hello @zopieux,

I'm encountering a similar issue with protobuf version incompatibility. Here's the error I'm getting:

```
[libprotobuf FATAL /Users/runner/work/ort-artifacts-staging/ort-artifacts-staging/onnxruntime/build/_deps/protobuf-src/src/google/protobuf/stubs/common.cc:83] This program was compiled against version 3.14.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.21.12).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/Users/solaoi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sentencepiece-sys-0.11.2/source/src/builtin_pb/sentencepiece_model.pb.cc".)
```

In my case, the conflict seems to be between the sbv2-api library mentioned in the ort README and the sentencepiece library used within the ctranslate2-rs library (https://github.com/jkawamoto/ctranslate2-rs).

Have you made any progress in resolving this issue? If you've found a solution or workaround, I'd greatly appreciate if you could share it.

**Comment by decahedron1** [comment]
This can be fixed by using a [dynamically linked](https://ort.pyke.io/setup/linking#dynamic-linking) build of ONNX Runtime.

**Comment by solaoi** [comment]
@decahedron1 
Thank you for your guidance on dynamic linking.
I successfully loaded the library using the information you provided from the following link:
https://github.com/microsoft/onnxruntime/releases/tag/v1.19.2
