### ISSUE TITLE
Inference failed when there are tensors of two datatypes in input.

### ISSUE THREAD

**Issue by VanderBieu** [pykeio/ort#298]
I have an ONNX model which takes one float tensor and three int tensors as input. The inference session works well in python version of onnxruntime. However it cannot work with "2.0.0-rc.6" version of ort.
The input is 
```
inputs!{
            "image_embeddings" => image_embeddings.view(),// f32
            "graph_points" => collated_points.view(), // i64
            "pairs" => collated_pairs.view(),// i64
            "valid" => collated_valid.view(),// i64
        }.unwrap();
```
in rust

```
image_embeddings = np.random.rand(1,256,64,64).astype(np.float32)
graph_points = np.random.rand(1, 40, 2).astype(np.int64)
pairs = np.random.rand(1, 40,16, 2).astype(np.int64)
valid = np.random.rand(1, 40,16).astype(np.int64)
inputs = {
    'image_embeddings': image_embeddings,
    'graph_points': graph_points,
    'pairs': pairs,
    'valid': valid
}

```
in python

No matter how I convert float to int or int to float the inference session kept failing with 
`{ code: InvalidArgument, msg: "Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(int64))" }`

**Comment by VanderBieu** [comment]
I think it might be the problem that the implementation of SessionInput is implemented using static type. To be specific the Session Input is constructed from HashMap<K,V> and Vec<(K,V)> so the value is automatically converted to f32 or i64 in order to match the type of V. My suggestion is that the input.rs should be reworked using more flexible structure.

**Comment by decahedron1** [comment]
Check the expected type of the graph's inputs using a program like [Netron](https://netron.app/).

**Comment by VanderBieu** [comment]
> Check the expected type of the graph's inputs using a program like [Netron](https://netron.app/).

I doublechecked, there is nothing wrong with input types. 
<img width="506" alt="image" src="https://github.com/user-attachments/assets/4763d42d-6ba2-470a-ad6f-5c298e7d9949">

**Comment by decahedron1** [comment]
How are you creating the tensors? Are you certain they are the expected dtype? (You can print [`Value::dtype`](https://ort.pyke.io/rustdoc/ort/struct.Value.html#method.dtype) to check.)
