### ISSUE TITLE
Support for sequence/map types

### ISSUE THREAD

**Issue by snc1011** [pykeio/ort#30]
I'm trying to execute the code below 
```
use ort::{
    tensor::{
        InputTensor,
        DynOrtTensor,
        FromArray,
        OrtOwnedTensor
    },
    Environment,
    LoggingLevel,
    SessionBuilder,
    OrtResult
};
use polars::{
    datatypes::Float32Type,
    prelude::*
};
use ndarray::IxDyn;


fn main () -> OrtResult<()> {

    //Lendo o dataframe usando Polars
    let dataframe = CsvReader::from_path("random_df.csv")
        .unwrap()
        .has_header(false)
        .finish()
        .unwrap()
        .to_ndarray::<Float32Type>()
        .unwrap();

    //Criando o ambiente
    let environment = Environment::builder()
	    .with_name("random_df_environment")
	    .with_log_level(LoggingLevel::Warning)
	    .build()?
	    .into_arc();

    //Criando a sessão
    let session = SessionBuilder::new(&environment)?
	    .with_model_from_file("random_df.onnx")?;

    let input = vec![
        InputTensor::from_array(dataframe.into_dyn())
    ];

    let outputs: Vec<DynOrtTensor<ndarray::Dim<ndarray::IxDynImpl>>> = session
        .run(input)
        .unwrap();
    let scores = &outputs[0];
    let scores: OrtOwnedTensor<'_, i64, IxDyn> = scores.try_extract()?;
    let scores = scores.view();
    let scores = scores.view();
    println!("{:}", scores);
    Ok(())
}
```

But i'm getting the Error: PointerShouldBeNull("CastTypeInfoToTensorInfo")
I googled it but didn't find a thing, could anyone help?

**Comment by snc1011** [comment]
Sure, https://drive.google.com/file/d/1s5iQBO6lYx2S2YfcDA4S3FDJMpjWYsNK/view?usp=share_link

**Comment by sudo-carson** [comment]
The error occurs because the graph contains an output with type `sequence<map<int64,float32>>`, which `ort` does not currently support.

**Comment by snc1011** [comment]
is there a workaround for this? This is a Logistic Regression model trained with random data for test purposes

**Comment by sudo-carson** [comment]
Not at the moment, no

**Comment by snc1011** [comment]
To anyone who might face a similar problem, there's a quick solution: when serializing the model to the onnx format, remember to "deactivate" the ZipMap, in python pass the `{'zipmap': False}` dict to the `convert_sklearn` or `to_onnx`'s _options_ parameter as shown:

```
initial_type = [('float_input', FloatTensorType([None, train_x.shape[1]]))]
onnx = convert_sklearn(clf, initial_types=initial_type, options={'zipmap': False})
with open("lr_iris.onnx", "wb") as f:
    f.write(onnx.SerializeToString())
```

**Comment by ikrivosheev** [comment]
@decahedron1 Did my PR(https://github.com/pykeio/ort/pull/102) close the issue? Or I forgot about something?

**Comment by decahedron1** [comment]
@ikrivosheev All that's required after #102 is just the logic to convert between ORT `Value`s and Rust `HashMap`/`Vec`s in `src/value.rs`.

**Comment by ikrivosheev** [comment]
@decahedron1 sorry for the delay... I worked on other problem. Do you need help with release 2.0? I saw, that you already added convert logic.
