### ISSUE TITLE
[Feature] Make clog optional

### ISSUE THREAD

**Issue by cyanic-selkie** [pykeio/ort#304]
When building onnxruntime with the flag `--cmake_extra_defines=onnxruntime_BUILD_UNIT_TESTS=OFF`, `ort-sys` building fails with the following error:

```
error: could not find native static library `clog`, perhaps an -L flag is missing?
error: could not compile `ort-sys` (lib) due to 1 previous error
``` 

The reason you might want to do that is because it drastically speeds up compilation times when tests aren't compiled.

**Comment by cyanic-selkie** [comment]
@decahedron1 Apparently, `re2` needs to be optional as well - it compiles for me when I take it out.

P.S. Your speed of fixing these issues is absurd, and very much appreciated, thanks!

**Comment by decahedron1** [comment]
Weird, for me (Windows x64, ONNX Runtime 1.19.2) re2 isn't compiled when unit tests are disabled, but ONNX Runtime still depends on a few symbols, causing undefined symbol errors if I make the re2 link optional. Compiling with `--build_shared_lib` gets it to compile re2.lib, though. I wonder if there's a misconfiguration upstream. What platform/branch are you using?

**Comment by cyanic-selkie** [comment]
You're right, running `cargo build --lib` passes, but `cargo test` fails due to missing symbols for me.

I'm on linux, compiling `onnxruntime @ 5aabc53121` with:

`./build.sh --cmake_extra_defines=onnxruntime_BUILD_UNIT_TESTS=OFF --config Release --parallel --compile_no_warning_as_error --skip_submodule_sync --update --build --build_dir build/linux`

It does seem like an upstream issue. I'll open an issue there.
