### ISSUE TITLE
Build failure when feature "half" is not enabled

### ISSUE THREAD

**Issue by jawj** [pykeio/ort#305]
In `src/tensor/types.rs` there are always references made to `Float16` and `Bfloat16`, but these enum values only exist when `#[cfg(feature = "half")]`.

Hence these errors: https://github.com/Anush008/fastembed-rs/actions/runs/11420241429/job/31775708538?pr=120

**Comment by jawj** [comment]
Thanks for the quick response! And sorry, but any chance of another RC release with this?

**Comment by decahedron1** [comment]
With rc.7 being released just yesterday and rc.8 today, probably not for at least another week, unfortunately.
