### ISSUE TITLE
Feedback for “I/O Binding”

### ISSUE THREAD

**Issue by bradneuman** [pykeio/ort#312]
Page appears to be missing? I don't see it in blame history either

**Comment by decahedron1** [comment]
Yep, never got around to writing it, eventually forgot about it... 🙃

For now the rustdoc has a little bit of info: [`IoBinding`](https://docs.rs/ort/2.0.0-rc.8/ort/struct.IoBinding.html). Unfortunately ONNX Runtime's own documentation about the topic is a little scarce. I'll try to have a more in-depth doc page written up tomorrow.

**Comment by bradneuman** [comment]
Makes sense, so far I've found the example in the API docs page useful
