### ISSUE TITLE
How to compile onnxrruntime.dll into Windows

### ISSUE THREAD

**Issue by monkeycc** [pykeio/ort#313]
```
ORT_DYLIB_PATH
D:\onnxruntime-win-x64-gpu-1.19.0\lib\onnxruntime.dll
```
Already set

In the Windows environment
How to compile onnxrruntime.dll,
Package together into the exe directory
I want to package it for others to use, and I need to integrate onnxruntime

**Comment by decahedron1** [comment]
Sorry, I'm not entirely sure what you mean.

If you want to distribute your application *with the .DLL* and without requiring the user to set the `ORT_DYLIB_PATH` environment variable, you can use [`ort::init_from`](https://docs.rs/ort/2.0.0-rc.8/ort/fn.init_from.html). See [the "programmatically" section in the `load-dynamic` docs](https://ort.pyke.io/setup/linking#point-ort-to-the-dylib); if `onnxruntime.dll` is in the same directory as the `.exe`, this can be achieved with `ort::init_from(std::env::current_exe().unwrap().join("onnxruntime.dll")).commit()?`.

If you want to distribute your application as a single `.exe` file, you'll have to compile ONNX Runtime from source for **static linking**; however, static linking does not work with CUDA/TensorRT. See [the ONNX Runtime build documentation](https://onnxruntime.ai/docs/build/inferencing.html) to compile from source - to compile with static linking, omit the `--build_shared_lib` argument. To link `ort` to the compiled binaries, see [the docs on static linking](https://ort.pyke.io/setup/linking#static-linking).
