### ISSUE TITLE
Building multiple ort-sys with `download-binaries` may fail

### ISSUE THREAD

**Issue by qryxip** [pykeio/ort#322]
When you use ort with `download-binaries` both in `dependencies` and in `build-dependencies`, in the following code, in-progress `lib_dir` may be used.

<https://github.com/pykeio/ort/blob/548bfed208ac340be431950aa79c594955a681a0/ort-sys/build.rs#L462-L467>

Perhaps `fetch-models` has the same problem.

### Solutions I come up with

1. Lock `lib_dir` with [fs4](https://docs.rs/crate/fs4) or something

    FYI, [Cargo calls `flock(2)` and `FileLockExt` directly](https://docs.rs/cargo/0.83/cargo/util/struct.Filesystem.html).

2. Extract the TGZ in a temporary directory and move it to `lib_dir`

3. Detect if `lib_dir` is in-progress and just panic with a human readable message

### Reproduction

Not yet, but I feel it happens for EPs.

**Comment by decahedron1** [comment]
Should be fixed by https://github.com/pykeio/ort/commit/eb51646860bc2fc5728d879bdf542c0537acc6ea
