### ISSUE TITLE
Loading large T5 Models > 2GB efficiently

### ISSUE THREAD

**Issue by chriskyndrid** [pykeio/ort#39]
I have a model I've converted to onnx format that is > 2GB. This results in a number of model.onnx files. I'm grappling the an efficient approach to loading the model. 

For other models I will:

```rust
pub static ENCODER_MODEL: Lazy<Vec<u8>> = Lazy::new(|| {
    let model_path = PathBuf::from(&*GLOBAL_AI_INCLUDE_ROOT).join("encoder/model/model.onnx");
    let mut file = File::open(model_path).unwrap();
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer).unwrap();
    buffer
});
```
and then do something like:

```rust
pub struct SentenceEncoder<'s> {
    session: InMemorySession<'s>,
}

impl SentenceEncoder<'_> {
    pub fn new() -> SystemSyncResult<Self> {
        let session = SessionBuilder::new(&ENVIRONMENT)?
            .with_optimization_level(GraphOptimizationLevel::Level1)?
            .with_model_from_memory(&*ENCODER_MODEL)?;

        Ok(Self { session })
    }

    //more code....

}
```

I then have a dedicated threadpool that loads a specified number of threads and reuses the sessions across calls to ensure we can run inference in parallel. Callers can issue calls over a crossbeam channel to a watcher that prioritizes the incoming calls and dispatches them to a processing thread. The thread pics it up and based on the inference request type elects the appropriate session to run.

With most models the above strategy works great, and all session share the ENCODER_MODEL memory. This  particular T5 model(it's a t5-large grammar synthesis pretrained model), when I convert it to onnx format, I end up with a bunch of files(model.onnx, onnx__MatMul_XXXXm shared.weights) due to Googles Protocol Buffers serialization format and size limitations. So the actual model.onnx file is very small and the rest of the model contents are located in the rest of the files. 

Is there a way I can pass the model into ort from memory similar to how I'm doing with other models? Additionally, is there something I'm overlooking here(I'm new to using this crate)? Does the Microsoft runtime efficiently share the model representation in memory internally for sessions loaded with the same model file, so multiple calls to ```with_model_from_file()``` won't result in unnecessary memory allocation? Am I misunderstanding something here?

Any help on this would be appreciated. Admittedly I haven't finished the implementation of this T5 model in rust yet, so I'm a bit preemptive in my questions. 

Thanks again for the work on this crate!

**Comment by sudo-carson** [comment]
> Is there a way I can pass the model into ort from memory similar to how I'm doing with other models?

Not that I'm aware of with models using the external data format. External data referenced in ONNX graphs can only point to a file.

> Does the Microsoft runtime efficiently share the model representation in memory internally for sessions ran against the same model file, so multiple calls to with_model_from_file() won't result in unnecessary memory allocation? 

No, each call will re-load the entire model and its (external) weights.

**Comment by chriskyndrid** [comment]
Thanks for the quick reply, that's a bummer and seems like an area of improvement for the onnxruntime. In any case, I'll have to handle that particular model differently than. 

Have a wonderful evening.
