### ISSUE TITLE
Is it possible to use ORT for training?

### ISSUE THREAD

**Issue by ianpurton** [pykeio/ort#51]
onnxruntime supports training see https://github.com/microsoft/onnxruntime-training-examples

Is this possible with ORT?

If so could someone give an example of how this might work?

My end goal is to see if I can fine tune models such as LLama using Rust, without jumping into python.

**Comment by sudo-carson** [comment]
Training is not in scope for `ort`, sorry. If you need to train in Rust, you might want to try [`tch`](https://crates.io/crates/tch), a Rust wrapper for Torch.
