### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by mush42** [pykeio/ort#52]
Hi,

The title says it all. Android is an officially supported target for onnxruntime and Rust.

Microsoft provides pre-built artifacts for android on [Maven](https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime)

Moreover, onnxruntime provides Android-specific execution providers. See [Execution Providers](https://onnxruntime.ai/docs/execution-providers/)

Best
Musharraf

**Comment by sudo-carson** [comment]
Android is supported (but not tested), see #45

I don't have an Android environment to test it with yet, but I will promptly fix any build issues regarding Android should they arise.

**Comment by mush42** [comment]
Thanks @sudo-carson  

I'm about to start an Android project with `ort`. I'll report back any issues I may encounter.

Best
Musharraf
