### ISSUE TITLE
Setting up `ort` as a dependency for CI pipeline

### ISSUE THREAD

**Issue by guillaume-be** [pykeio/ort#53]
Hello,

I am in the final stages of integrating ONNX support for a project via the `ort` bindings. I have everything working well on my machine, and working on the CI when pinning the dependency to `ort = {version="=1.14.3", optional = true, default-features = false, features = ["half"]}`. I downloaded the ONNXRuntime library and set up my `ORT_DYLIB_PATH` to the `.dll` downloaded manually.

For the CI I would like the download to happen automatically (since maintaining the download path per OS/version in the github cations is a bit of a hassle). This was working fine with version `1.14.3`, as can be seen by [this CI run](https://github.com/guillaume-be/rust-bert/actions/runs/5094442250/jobs/9158258319). I cannot get the same behaviour with `1.14.6`, see for example [this run](https://github.com/guillaume-be/rust-bert/actions/runs/5094308486/jobs/9157958759).

Could you please help me understand how I should set my features/CI to allow a migration from `1.14.3` to `1.14.6`? For information my actions file for ONNX tests is at availaable [here](https://github.com/guillaume-be/rust-bert/blob/8139e9563e6a81eeeb801eeb7df380268a1c6489/.github/workflows/continuous-integration.yml#L143), and this is my [`Cargo.toml`](https://github.com/guillaume-be/rust-bert/blob/onnx-runtime/Cargo.toml)

**Comment by sudo-carson** [comment]
Sorry, it was [a mistake on my end](https://github.com/pykeio/ort/commit/481d025072cf95f35e67237e4fd5957c7bb79c55). This [should be fixed](https://github.com/pykeio/ort/commit/df47ee24f5d3eeab7027e90f27aded9ec49de259) with `1.14.8`. I tested your workflow locally and got all tests passing with 1.14.8.

**Comment by guillaume-be** [comment]
Thank you @sudo-carson , it works great. https://github.com/guillaume-be/rust-bert now supports ONNX Runtime via the bindings you are proposing in `ort` 👍
