### ISSUE TITLE
FR: Remove `fetch-models` from default features

### ISSUE THREAD

**Issue by steventrouble** [pykeio/ort#59]
I've noticed that it's a common practice in Rust to leave expensive features off by default. For example, many packages don't include their derive macros as default features because they increase compile times.

I think it might be good to remove `fetch-models` from the default features to match this convention.

What do you think? Any objections?

**Comment by decahedron1** [comment]
No objections. I've been wanting to reduce compile times as much as possible and I think disabling or outright removing `fetch-models` would be a good start. As far as I'm aware, the feature is seldom used anyways.

**Comment by decahedron1** [comment]
`fetch-models` is no longer enabled by default as of v1.15.0.
