### ISSUE TITLE
Support for boolean input tensor from ndarray

### ISSUE THREAD

**Issue by hobincar** [pykeio/ort#60]
Hello. First of all, thank you for sharing this great repo!

My onnx model uses boolean array as input, but converting from boolean ndarray to InputTensor seems not working (I tried with f64 ndarray and it works fine).
![image](https://github.com/pykeio/ort/assets/17702664/2760f876-0016-4158-ad4c-0361044e88ec)

I recognizes that there is a PR (https://github.com/pykeio/ort/pull/58) which tries to fix it, but I also saw another PR (https://github.com/pykeio/ort/pull/41) that shows that you are working on the next release version.

My question is, will it be fixed on the next release version? I tried to figure it out myself, but it was hard because the code structure seems to be changed.

Thank you!

**Comment by decahedron1** [comment]
Yes, bool tensors will be supported in 1.15 and are currently implemented in #41 as of https://github.com/pykeio/ort/pull/41/commits/516be59a974945c14c9bf2fa140abd6acbc68ad1.

**Comment by hobincar** [comment]
Thanks! I’ll try https://github.com/pykeio/ort/commit/516be59a974945c14c9bf2fa140abd6acbc68ad1 until the next version is released.
