### ISSUE TITLE
problems building on x86 on windows

### ISSUE THREAD

**Issue by beqabeqa473** [pykeio/ort#65]
Hello.

I am encountering problems while building ort for x86 on windows.

```error[E0277]: `unsafe extern "stdcall" fn(*const OrtCustomOp, usize) -> OrtCustomOpInputOutputCharacteristic` doesn't implement `Debug`                                                                                                         
    --> C:\Users\beqap\.cargo\registry\src\github.com-1ecc6299db9ec823\ort-1.15.1\src\sys.rs:2965:2                     
     |                                                                                                                  
2952 | #[derive(Debug, Copy, Clone)]                                                                                    
     |          ----- in this derive macro expansion                                                                    
...                                                                                                                     
2965 |     pub GetInputCharacteristic: ::std::option::Option<_system!(unsafe fn(op: *const OrtCustomOp, index: size_t) -> OrtCustomOpInputOutputCharacteristic...                                                                               
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `unsafe extern "stdcall" fn(*const OrtCustomOp, usize) -> OrtCustomOpInputOutputCharacteristic` cannot be formatted using `{:?}` because it doesn't implement `Debug`                                  
     |                                                                                                                  
     = help: the trait `Debug` is not implemented for `unsafe extern "stdcall" fn(*const OrtCustomOp, usize) -> OrtCustomOpInputOutputCharacteristic`                                                                                           
     = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)                                                                                                                   
 ```

**Comment by decahedron1** [comment]
Hmm, I can't reproduce this build error with rustc v1.71 building for `--target i686-pc-windows-msvc`. What is your rustc version, and which target are you compiling for?

**Comment by beqabeqa473** [comment]
I am compiling for i686-pc-windows-msvc and using rustc v1.69

On 7/19/23, Carson M. ***@***.***> wrote:
> Hmm, I can't reproduce this build error with rustc v1.71 building for
> `--target i686-pc-windows-msvc`. What is your rustc version, and which
> target are you compiling for?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/pykeio/ort/issues/65#issuecomment-1642467992
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
Updating rustc resolved a problem, thank you
