### ISSUE TITLE
Do we really need `ort::session::InMemorySession`?

### ISSUE THREAD

**Issue by SunDoge** [pykeio/ort#71]
It seems that the lifetime is not necessary.

```python
import torch

linear = torch.nn.Linear(2, 4)
x = torch.tensor([0.1, 0.2])
y = linear(x)
print(y)

torch.onnx.export(
    linear,
    (torch.rand(1, 2),),
    'linear.onnx',
    input_names=["x"],
    output_names=['y'],
    dynamic_axes={'x': {0: 'B'}, 'y': {0: 'B'}}
)
```

```rust
use std::sync::Arc;

use ndarray::{ArrayD, CowArray};
use ort::{tensor::OrtOwnedTensor, Environment, ExecutionProvider, SessionBuilder, Value};

fn main() {
	let environment = Arc::new(
		Environment::builder()
			.with_execution_providers([ExecutionProvider::CPU(Default::default())])
			.build()
			.unwrap()
	);

	let mb = std::fs::read("linear.onnx").unwrap();
	let session = SessionBuilder::new(&environment).unwrap().with_model_from_memory(&mb).unwrap();
	drop(mb);

	let x: ArrayD<f32> = ndarray::arr2(&[[0.1, 0.2]]).into_dyn();
	let x = CowArray::from(x);
	let outputs = session.run(vec![Value::from_array(session.allocator(), &x).unwrap()]).unwrap();
	let y: OrtOwnedTensor<f32, _> = outputs[0].try_extract().unwrap();
	dbg!(y.view().clone().into_dyn());
}
```

```patch
diff --git a/src/session.rs b/src/session.rs
index 2ef923f..c633613 100644
--- a/src/session.rs
+++ b/src/session.rs
@@ -481,7 +481,7 @@ impl SessionBuilder {
        }
 
        /// Load an ONNX graph from memory and commit the session.
-       pub fn with_model_from_memory(self, model_bytes: &[u8]) -> OrtResult<InMemorySession<'_>> {
+       pub fn with_model_from_memory(self, model_bytes: &[u8]) -> OrtResult<Session> {
                let mut session_ptr: *mut sys::OrtSession = std::ptr::null_mut();
 
                let env_ptr: *const sys::OrtEnv = self.env.ptr();
@@ -533,7 +533,8 @@ impl SessionBuilder {
                        inputs,
                        outputs
                };
-               Ok(InMemorySession { session, phantom: PhantomData })
+               // Ok(InMemorySession { session, phantom: PhantomData })
+               Ok(session)
        }
 }
```

**Comment by SunDoge** [comment]
And the C API does not mention that we have to keep `model_bytes` alive while using `Session`. `Session` should parse the `model_bytes` and keep the parsed params and graph in memory so it can outlive the `model_bytes`.

**Comment by decahedron1** [comment]
> `Session` should parse the model_bytes and keep the parsed params and graph in memory so it can outlive the `model_bytes`.

Not always, For `.ort` models, we enable `session.use_ort_model_bytes_directly`:

> You may also enable the option to use the model bytes directly by setting the SessionOptions config entry `session.use_ort_model_bytes_directly` to `1`. This may reduce the peak memory usage of ONNX Runtime Mobile, but you will need to guarantee that the model bytes are valid throughout the lifespan of the ORT session.

https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html

**Comment by SunDoge** [comment]
I see. But by default 

> If a session is created using an input byte array containing the ORT format model data, by default we will copy the model bytes at the time of session creation to ensure the model bytes buffer is valid.

The api [with_model_from_memory](https://docs.rs/ort/1.15.2/ort/session/struct.SessionBuilder.html#method.with_model_from_memory) should be consistent with [with_model_from_file](https://docs.rs/ort/1.15.2/ort/session/struct.SessionBuilder.html#method.with_model_from_file). And `ort::session::InMemorySession` should be created with another api, e.g. `with_model_from_memory_directly`.
