### ISSUE TITLE
The difference in inference time between tch and onnx 

### ISSUE THREAD

**Issue by SeolJeongA** [pykeio/ort#82]
Hi, 

In my `rust` code, there is the difference in inference time between `tch` model and `onnx` session.
tch model is much faster than onnx session. I wonder why.

Actually, there was little difference between the two in `python`, but there is a lot in `rust`.
I have no idea, I really want to solve this problem. 

thank you,

**Comment by decahedron1** [comment]
If you are using a non-CPU execution provider, `ort` could be gracefully falling back to run on CPU - see [here](https://github.com/pykeio/ort#im-using-a-non-cpu-execution-provider-but-its-still-using-the-cpu) to debug.

**Comment by SeolJeongA** [comment]
Thank you! 

Actually, I'm trying to use `ort` for inferencing onnx model in `Jetson nano orin`. 
But it doesn't seem to support a non-CPU execution provider. the CPU is only used when my code runs.
Is there any way to bind the `GPU` in my device, `Jetson nano orin`? Please let me know.

**Comment by decahedron1** [comment]
Microsoft doesn't provide prebuilt binaries for Jetson with CUDA, so you'll have to build ONNX Runtime from source. See here: https://onnxruntime.ai/docs/build/eps.html#nvidia-jetson-tx1tx2nanoxavier
