### ISSUE TITLE
Does "Session" implement clone?

### ISSUE THREAD

**Issue by kingzcheung** [pykeio/ort#84]
https://github.com/pykeio/ort/blob/561870accbaf99b8b226a522f3d8ab59ed9b9d6f/src/session.rs#L557

```rust
#[derive(Debug,Clone)]
pub struct Session {
//...
}
```

**Comment by decahedron1** [comment]
`Session`s are not clonable but `SessionBuilder`s will be in [v2.0](https://github.com/pykeio/ort/pull/78).
