### ISSUE TITLE
When running cargo build --release cant find ./program: error while loading shared libraries: libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Quicksticks-oss** [pykeio/ort#85]
./program: error while loading shared libraries: libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory

Cargo.toml
```
[package]
name = "antivirus"
version = "0.1.0"
edition = "2021"

[profile.dev]
rpath = true

[profile.release]
rpath = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ort = "1.15.2"
ndarray = "0.15.6"```

program/target/release ls:
``antivirus  
antivirus.d  
build  
deps  
examples  
incremental  
libonnxruntime.so  
libonnxruntime.so.1.15.1``

Anyway I can fix this so I can share the binary without cargo run?

**Comment by decahedron1** [comment]
Have you also set the rpath compile flag?

> In `.cargo/config.toml`:
> 
> ```toml
> [target.x86_64-unknown-linux-gnu]
> rustflags = [ "-Clink-args=-Wl,-rpath,\\$ORIGIN" ]
> 
> # do this for all Linux targets as well
> ```

Otherwise I believe you could use the `LD_LIBRARY_PATH` environment variable or the `load-dynamic` feature.

**Comment by Quicksticks-oss** [comment]
Thanks I was wondering how I can add the load-dynamic feature?

**Comment by decahedron1** [comment]
In `Cargo.toml`:
```toml
[dependencies]
ort = { version = "1.15.2", features = [ "load-dynamic" ] }
```

**Comment by Quicksticks-oss** [comment]
This works so well thanks! :heart:
