### ISSUE TITLE
TensorRT provider failing with default options

### ISSUE THREAD

**Issue by bugeats** [pykeio/ort#86]
```toml
ort = { version = "1.15.2", features = ["load-dynamic", "tensorrt"] }
```

```rust
Environment::builder()
   .with_execution_providers([ExecutionProvider::TensorRT(Default::default())])
   .build()?
   .into_arc();
```

```
ort::execution_providers: An error occurred when attempting to register `TensorrtExecutionProvider`: key/value cannot be empty
```

I spent some time poking around the onnxruntime and ort code. It looks like maybe onnxruntime is [not getting the provider options somehow](https://github.com/microsoft/onnxruntime/blob/v1.15.1/onnxruntime/core/session/provider_bridge_ort.cc#L1685)?

**Comment by bharrisau** [comment]
See
- https://github.com/pykeio/ort/blob/ba9df1923026fcdf7f4e13152a8d5b8a901ffc0f/src/execution_providers.rs#L484
- https://github.com/pykeio/ort/blob/ba9df1923026fcdf7f4e13152a8d5b8a901ffc0f/src/execution_providers.rs#L624

`map_keys!` needs in include a call to `.retain(|k, v| !v.is_empty())` to remove all the empty strings for default arguments.

**Comment by bharrisau** [comment]
I've just used the v2 branch in the mean time.

**Comment by bharrisau** [comment]
You can test if my patch fixes it with

`ort = { git = "https://github.com/bharrisau/ort.git", branch = "trt_config" , ... }`

Else move to the v2 branch that seems to work for me

`ort = { git = "https://github.com/pykeio/ort.git", branch = "v2" , ... }`
