### ISSUE TITLE
Multiple GPUs/ExecutionDevices: How to select one for inference?

### ISSUE THREAD

**Issue by marcown** [pykeio/ort#90]
Hey,

first of all: thanks for the nice repo!

Having multiple CUDA or DirectML or OpenVino Devices: How do select the one that you want to use?

Thanks for any help :)

**Comment by decahedron1** [comment]
Most execution providers let you specify a device ID with the `device_id` field in their options struct. For example, with CUDA:

```rs
let environment = Environment::builder()
    .with_execution_providers([
        ExecutionProvider::CUDA(CUDAExecutionProviderOptions {
            device_id: 0,
            ..Default::default()
        })
    ])
```

See the [`execution_providers` docs](https://docs.rs/ort/latest/ort/execution_providers/index.html) for more options.
