### ISSUE TITLE
Direct ML Compile Error

### ISSUE THREAD

**Issue by marcown** [pykeio/ort#91]
Hey there,

when compiling for windows 1809 using direct ml with cargo

```yaml
[dependencies.ort]
version =  "1.15.2"
features = ["download-binaries", "directml"] 
```

I get the following error:
```bash
error: linking with `link.exe` failed: exit code: 1120
...
  = note: libort-823b36f3ee700ecc.rlib(ort-823b36f3ee700ecc.ort.b1d99b0d4efe1b77-cgu.11.rcgu.o) : error LNK2019: unresolved external symbol OrtSessionOptionsAppendExecutionProvider_DML referenced in function _ZN3ort19execution_providers17ExecutionProvider5apply17h70344b19a4319081E
```

Could the reason be that direct ml is not installed in windows 1809? I tried to install it with

nuget install Microsoft.AI.DirectML -Version 1.12.1

Is there another, better way? I cannot upgrade the windows version at the momen

Thanks!

**Comment by decahedron1** [comment]
IIRC the `download` strategy does not have binaries compiled with DirectML support, you'd have to compile ONNX Runtime yourself and use the `system` strategy.

**Comment by marcown** [comment]
This worked! Thanks for the fast reponse :)
